[window]
decorations = "Full"
# startup_mode = "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen"
startup_mode = "Maximized"
opacity = 0.8

[scrolling]
history = 30000
multiplier = 3

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
size = 13

[colors.primary]
background = "#3b4252"
foreground = "#eceff4"

